mod-name: CryoTanks
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - CryoTanks
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    version: 4.2.3
    location: s3
  B9PartSwitch:
    version: 2.20.0
    location: s3
  CommunityResourcePack:
    version: 1.4.2
    location: s3
  DynamicBatteryStorage:
    tag: 2.3.0
    location: github
    repository: post-kerbin-mining-corporation/DynamicBatteryStorage
deploy:
  SpaceDock:
    enabled: false  # activate/deactivate this deployment script
    mod-id: 558  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: false  # activate/deactivate this deployment script
    mod-id: 220671  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
